w6d5/cats_project/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
end

w6d5/cats_project/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string           not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper
    COLORS = ["black", "orange", "grey", "white", "multi-colored", "naked"]
    validates :birth_date, :color, :name, :sex, presence: true
    validate :check_sex
    validates :color, :inclusion => {:in => COLORS}

    def check_sex
        if sex != "M" && sex != "F"
            errors[:sex] << "Wrong value for sex"
        end
    end
    
    

    def age
        time_ago_in_words(birth_date)
    end

    
end

w6d5/cats_project/app/controllers/cats_controller.rb
class CatsController < ApplicationController

    def index
        @cats = Cat.all
        render :index
    end

    def show
        @cat = Cat.find(params[:id])
        render :show
    end

    def new
        @cat = Cat.new
        render :new
    end

    def create
        @cat = Cat.new(cat_params)
        if @cat.save
            redirect_to cat_url(@cat)
        else
            render :new
        end
    end

    private
    def cat_params
        params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
    end

end

w6d5/cats_project/app/views/cats/edit.html.erb
<h1>Edit your Cat</h1>


<form action = "<%= cat_url(@cat)%>" method = "POST"> 
    <input type = "hidden" name = "_method" value = "PATCH">
    <label>Birthday 
    <input 
        type="date"
        name = "cat[birth_date]"
        value = "<%= @cat.birth_date%>"> 
    </label>

    <label>Color 
    <select name = "cat[color]" > 
        <option disabled selected> Select a color</option>
        <option value = "black">Black</option>
        <option value = "orange">Orange</option>
        <option value = "grey">Grey</option>
        <option value = "white">White</option>
        <option value = "multi-colored">Multi-Colored</option>
        <option value = "naked">Naked</option>
        
    </select> 
    </label>

    <label>Name
    <input 
        type="text"
        name = "cat[name]"
        value = "<% @cat.name%>"> 
    </label>

    <label>Sex
    <input type="radio" id = "male" name = "cat[sex]" value = "M">
    <label for = "male">Male</label>
    <input type="radio" id = "female" name = "cat[sex]" value = "F">
    <label for = "female">Female</label>
    </label>
    
    <input type= "submit"
        value = "Submit changes">
</form>

w6d5/cats_project/app/views/cats/index.html.erb
<h1> All Cats </h1>
    <ul>
        <% @cats.each do |cat| %>
            <li><a href="<%=cat_url(cat)%>"><%=cat.name%></a></li>
        <% end %>
    </ul>


<%# "/cats/#{cat.id}"  %>

w6d5/cats_project/app/views/cats/new.html.erb
<h1>Build your Cat</h1>


<form action = "<%= cats_url%>" method = "POST"> 
    <label>Birthday 
    <input 
        type="date"
        name = "cat[birth_date]"> 
    </label>

    <label>Color 
    <select name = "cat[color]"> 
        <option disabled selected> Select a color</option>
        <option value = "black">Black</option>
        <option value = "orange">Orange</option>
        <option value = "grey">Grey</option>
        <option value = "white">White</option>
        <option value = "multi-colored">Multi-Colored</option>
        <option value = "naked">Naked</option>
    </select> 
    </label>

    <label>Name
    <input 
        type="text"
        name = "cat[name]"> 
    </label>

    <label>Sex
    <input type="radio" id = "male" name = "cat[sex]" value = "M">
    <label for = "male">Male</label>
    <input type="radio" id = "female" name = "cat[sex]" value = "F">
    <label for = "female">Female</label>
    </label>
    
    <input type= "submit"
        value = "Create cat">
</form>

w6d5/cats_project/app/views/cats/show.html.erb
<h1><%= @cat.name%></h1>

<table>
    <thead>
        <tr>
            <th colspan="1">Attribute</th>
			<th colspan="1">Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Name</td>
          	<td><%= @cat.name%></td>
        </tr>
        <tr>
            <td>Color</td>
            <td><%= @cat.color%></td>
        </tr>
        <tr>
            <td>Sex</td>
            <td><%= @cat.sex%></td>
        </tr>
        <tr>
            <td>Birthday</td>
            <td><%= @cat.birth_date%></td>
        </tr>
  	</tbody>
</table>